version: '3.8'

services:
  app:
    image: almonium
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${LOCAL_PORT}:${LOCAL_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"
      GOOGLE_APPLICATION_CREDENTIALS: /app/service-account.json
    volumes:
      - ./service-account.json:/app/service-account.json
    env_file:
      - ./.env
