services:
  # ───────────────────────────────────────────────────────── app ──
  app:
    container_name: app
    image: almonium
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${LOCAL_PORT}:${LOCAL_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    env_file:
      - ./.env
    depends_on:
      - rabbitmq

  # ──────────────────────────────────────────────── rabbitmq ──
  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq
    ports:
      - ${RABBITMQ_HOST_PORT:-5672}:5672
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
