server:
  port: ${LOCAL_PORT}
  servlet:
    context-path: ${CONTEXT_PATH}
  forward-headers-strategy: framework

spring:
  config:
    import: optional:file:.env[.properties]
  profiles.active: ${SPRING_PROFILE}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    port: ${RABBITMQ_PORT}
    virtual-host: ${RABBITMQ_VHOST:/}
    listener.simple.retry:
      enabled: true
      initial-interval: 1s
      multiplier: 2.0
      max-attempts: 5
    publisher-confirm-type: correlated
    publisher-returns: true
  jpa:
    open-in-view: false
    properties.hibernate:
      default_schema: ${DB_SCHEMA}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  liquibase:
    contexts: ${SPRING_PROFILE}
    default-schema: ${DB_SCHEMA}

logging:
  level:
    org.springframework.transaction.interceptor: INFO
    root: INFO
  pattern.console: "%magenta(%d{HH:mm:ss.SSS}) %green(%5p) --- %cyan(%c{0}) : %msg%n%ex{5}"


# Custom Configurations
app:
  name: Almonium
  email:
    api-url: https://api.zeptomail.eu/v1.1/email
    api-key: ${ZEPTO_API_KEY}
    from-address: noreply@almonium.com
    from-name: Almonium
  auth:
    firebase:
      session-lifetime-seconds: 604800 # 7 days
      recent-login-seconds: 300 # 5 minutes
  books:
    publisher-secret: ${ALMONIUM_BOOKS_PUBLISHER_SECRET}
    processor-url: ${ALMONIUM_BOOKS_PROCESSOR_URL}

rabbitmq:
  exchange:
    events: events.exchange
    dlx: events.exchange.dlx
  queue:
    user-stream-setup:
      name: q.user.stream.setup
      routing-key: user.stream.setup.v1
      dlq-name: q.user.stream.setup.dlq
    user-languages-updated:
      name: q.user.languages.updated
      routing-key: user.languages.updated.v1
      dlq-name: q.user.languages.updated.dlq
    user-profile-updated:
      name: q.user.profile.updated
      routing-key: user.profile.updated.v1
      dlq-name: q.user.profile.updated.dlq
    user-target-language-added:
      name: q.user.target-language.added
      routing-key: user.target-language.added.v1
      dlq-name: q.user.target-language.added.dlq
    user-target-language-removed:
      name: q.user.target-language.removed
      routing-key: user.target-language.removed.v1
      dlq-name: q.user.target-language.removed.dlq
    subscription-status-changed:
      name: q.subscription.status.changed
      routing-key: subscription.status.changed.v1
      dlq-name: q.subscription.status.changed.dlq
    friendship-email-requested:
      name: q.friendship.email.requested
      routing-key: friendship.email.requested.v1
      dlq-name: q.friendship.email.requested.dlq
    user-deleted-stream:
      name: q.user.deleted.stream
      routing-key: user.deleted.v1
      dlq-name: q.user.deleted.stream.dlq
    user-deleted-stripe:
      name: q.user.deleted.stripe
      routing-key: user.deleted.v1
      dlq-name: q.user.deleted.stripe.dlq
    user-deleted-firebase:
      name: q.user.deleted.firebase
      routing-key: user.deleted.v1
      dlq-name: q.user.deleted.firebase.dlq
google:
  project-id: ${GOOGLE_PROJECT_ID}
  parent-location: global
  firebase.storage.bucket: ${FIREBASE_STORAGE_BUCKET}
  service-account-key-base64: ${GOOGLE_SERVICE_ACCOUNT_KEY_BASE64}

stream.api:
  key: ${STREAM_KEY}
  secret: ${STREAM_SECRET}

stripe:
  webhook.secret: ${STRIPE_WEBHOOK_SECRET}
  api.key: ${STRIPE_KEY}
  checkout:
    success-url: ${app.web-domain}/payment/success
    cancel-url: ${app.web-domain}/pricing?canceled=true
  return-url: ${app.web-domain}/settings/me?portal=from

external.api:
  # free/non-rated
  ngrams.url: https://api.ngrams.dev
  key:
    urban: ${RAPID_API_KEY}
    words: ${RAPID_API_KEY}
    wordnik: ${WORDNIK_KEY}
    yandex: ${YANDEX_KEY}
