server:
  port: ${BE_PORT}
  servlet:
    context-path: /api/v1

spring:

  ### Database Config
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    contexts: ${spring.profiles.active}

  # OAuth Configurations
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_ID}
            clientSecret: ${GOOGLE_SECRET}
            scope: profile,email

          facebook:
            clientId: ${FACEBOOK_ID}
            clientSecret: ${FACEBOOK_SECRET}

          apple:
            clientId: ${APPLE_ID}
            clientSecret: ${APPLE_SECRET}
            scope: name,email
            authorization-grant-type: authorization_code
            redirect-uri: https://api.almonium.com/api/v1/login/oauth2/code/apple

        provider:
          facebook:
            user-info-uri: https://graph.facebook.com/me?fields=id,first_name,last_name,name,email,picture
          apple:
            user-info-uri: https://appleid.apple.com/auth/userinfo
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token

  config:
    import:
      - optional:file:.env[.properties]
  mail:
    host: smtppro.zoho.eu
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 3000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.transaction.interceptor: TRACE
    com.almonium: DEBUG
    root: INFO
    org:
      hibernate:
        info: info
        SQL: debug
        orm.jdbc.bind: trace
        stat: debug
        SQL_SLOW: info
        cache: debug
        type.descriptor.sql.BasicBinder: trace
  pattern:
    console: "%magenta(%d{HH:mm:ss.SSS}) %green(%5p) --- %cyan(%c{0}) : %msg%n%ex{5}"

# Google Cloud Configurations
google:
  projectId: ${GOOGLE_PROJECT_ID}
  parentLocation: global

# Custom Configurations
app:
  server:
    domain: ${SERVER_DOMAIN}

  auth:
    tokenExpirationDurationMillis: 864000000
    tokenSigningSecret: ${TOKEN_SECRET}

  oauth2:
    authorizedRedirectUris: ${app.server.domain}/oauth2/redirect

# External API keys
external:
  api:
    key:
      urban: ${URBAN_KEY}
      wordnik: ${WORDNIK_KEY}
      yandex: ${YANDEX_KEY}
      words: ${WORDS_KEY}
      oxford: ${OXFORD_KEY}
