package com.almonium.analyzer.translator.model.enums;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import lombok.Getter;

/**
 * Which English, which German (design V, table V5): the catalogue of varieties a learner may pick for a language.
 *
 * <p>Variety identity is independent of audio availability; the row order is by learner share, and the first entry
 * of each language is its default. Identity is the BCP-47 tag alone: the provider voice behind a variety lives in
 * {@link com.almonium.analyzer.translator.service.VoiceCatalogue}, not here. Every language has a default, including languages with no selector in the clients.
 * A bare language tag means no finer regional distinction is supported yet.
 */
@Getter
public enum LanguageVariety {
    EN_US(Language.EN, "en-US"),
    EN_GB(Language.EN, "en-GB"),
    EN_AU(Language.EN, "en-AU"),
    EN_IN(Language.EN, "en-IN"),

    ES_ES(Language.ES, "es-ES"),
    ES_MX(Language.ES, "es-MX"),
    ES_AR(Language.ES, "es-AR"),
    ES_CO(Language.ES, "es-CO"),

    PT_BR(Language.PT, "pt-BR"),
    PT_PT(Language.PT, "pt-PT"),

    FR_FR(Language.FR, "fr-FR"),
    FR_CA(Language.FR, "fr-CA"),
    FR_BE(Language.FR, "fr-BE"),
    FR_CH(Language.FR, "fr-CH"),

    DE_DE(Language.DE, "de-DE"),
    DE_AT(Language.DE, "de-AT"),
    DE_CH(Language.DE, "de-CH"),

    NL_NL(Language.NL, "nl-NL"),
    NL_BE(Language.NL, "nl-BE"),

    ZH_CN(Language.ZH, "zh-CN"),
    ZH_TW(Language.ZH, "zh-TW"),

    AF(Language.AF, "af"),
    SQ(Language.SQ, "sq"),
    AM(Language.AM, "am"),
    AR(Language.AR, "ar"),
    HY(Language.HY, "hy"),
    AS(Language.AS, "as"),
    AY(Language.AY, "ay"),
    AZ(Language.AZ, "az"),
    BM(Language.BM, "bm"),
    EU(Language.EU, "eu"),
    BE(Language.BE, "be"),
    BN(Language.BN, "bn"),
    BHO(Language.BHO, "bho"),
    BS(Language.BS, "bs"),
    BG(Language.BG, "bg"),
    CA(Language.CA, "ca"),
    CEB(Language.CEB, "ceb"),
    CO(Language.CO, "co"),
    HR(Language.HR, "hr"),
    CS(Language.CS, "cs"),
    DA(Language.DA, "da"),
    DV(Language.DV, "dv"),
    DOI(Language.DOI, "doi"),
    EO(Language.EO, "eo"),
    ET(Language.ET, "et"),
    EE(Language.EE, "ee"),
    FIL(Language.FIL, "fil"),
    FI(Language.FI, "fi"),
    FY(Language.FY, "fy"),
    GL(Language.GL, "gl"),
    KA(Language.KA, "ka"),
    EL(Language.EL, "el"),
    GN(Language.GN, "gn"),
    GU(Language.GU, "gu"),
    HT(Language.HT, "ht"),
    HA(Language.HA, "ha"),
    HAW(Language.HAW, "haw"),
    HE(Language.HE, "he"),
    HI(Language.HI, "hi"),
    HMN(Language.HMN, "hmn"),
    HU(Language.HU, "hu"),
    IS(Language.IS, "is"),
    IG(Language.IG, "ig"),
    ILO(Language.ILO, "ilo"),
    ID(Language.ID, "id"),
    GA(Language.GA, "ga"),
    IT(Language.IT, "it-IT"),
    JA(Language.JA, "ja-JP"),
    JV(Language.JV, "jv"),
    KN(Language.KN, "kn"),
    KK(Language.KK, "kk"),
    KM(Language.KM, "km"),
    RW(Language.RW, "rw"),
    GOM(Language.GOM, "gom"),
    KO(Language.KO, "ko-KR"),
    KRI(Language.KRI, "kri"),
    KU(Language.KU, "ku"),
    CKB(Language.CKB, "ckb"),
    KY(Language.KY, "ky"),
    LO(Language.LO, "lo"),
    LA(Language.LA, "la"),
    LV(Language.LV, "lv"),
    LN(Language.LN, "ln"),
    LT(Language.LT, "lt"),
    LG(Language.LG, "lg"),
    LB(Language.LB, "lb"),
    MK(Language.MK, "mk"),
    MAI(Language.MAI, "mai"),
    MG(Language.MG, "mg"),
    MS(Language.MS, "ms"),
    ML(Language.ML, "ml"),
    MT(Language.MT, "mt"),
    MI(Language.MI, "mi"),
    MR(Language.MR, "mr"),
    LUS(Language.LUS, "lus"),
    MN(Language.MN, "mn"),
    MY(Language.MY, "my"),
    NE(Language.NE, "ne"),
    NO(Language.NO, "no"),
    NY(Language.NY, "ny"),
    OR(Language.OR, "or"),
    OM(Language.OM, "om"),
    PS(Language.PS, "ps"),
    FA(Language.FA, "fa"),
    PL(Language.PL, "pl-PL"),
    PA(Language.PA, "pa"),
    QU(Language.QU, "qu"),
    RO(Language.RO, "ro"),
    RU(Language.RU, "ru-RU"),
    SM(Language.SM, "sm"),
    SA(Language.SA, "sa"),
    GD(Language.GD, "gd"),
    NSO(Language.NSO, "nso"),
    SR(Language.SR, "sr"),
    ST(Language.ST, "st"),
    SN(Language.SN, "sn"),
    SD(Language.SD, "sd"),
    SI(Language.SI, "si"),
    SK(Language.SK, "sk"),
    SL(Language.SL, "sl"),
    SO(Language.SO, "so"),
    SU(Language.SU, "su"),
    SW(Language.SW, "sw"),
    SV(Language.SV, "sv"),
    TL(Language.TL, "tl"),
    TG(Language.TG, "tg"),
    TA(Language.TA, "ta"),
    TT(Language.TT, "tt"),
    TE(Language.TE, "te"),
    TH(Language.TH, "th"),
    TI(Language.TI, "ti"),
    TS(Language.TS, "ts"),
    TR(Language.TR, "tr"),
    TK(Language.TK, "tk"),
    AK(Language.AK, "ak"),
    UK(Language.UK, "uk-UA"),
    UR(Language.UR, "ur"),
    UG(Language.UG, "ug"),
    UZ(Language.UZ, "uz"),
    VI(Language.VI, "vi"),
    CY(Language.CY, "cy"),
    XH(Language.XH, "xh"),
    YI(Language.YI, "yi"),
    YO(Language.YO, "yo"),
    ZU(Language.ZU, "zu"),

    ACE(Language.ACE, "ace"),
    ACH(Language.ACH, "ach"),
    AJG(Language.AJG, "ajg"),
    AA(Language.AA, "aa"),
    ARQ(Language.ARQ, "arq"),
    AWA(Language.AWA, "awa"),
    BFY(Language.BFY, "bfy"),
    BGQ(Language.BGQ, "bgq"),
    BQI(Language.BQI, "bqi"),
    BAN(Language.BAN, "ban"),
    BAL(Language.BAL, "bal"),
    BJN(Language.BJN, "bjn"),
    BCI(Language.BCI, "bci"),
    BA(Language.BA, "ba"),
    BAR(Language.BAR, "bar"),
    BEJ(Language.BEJ, "bej"),
    BEM(Language.BEM, "bem"),
    BEW(Language.BEW, "bew"),
    BHB(Language.BHB, "bhb"),
    BIK(Language.BIK, "bik"),
    BRX(Language.BRX, "brx"),
    PCC(Language.PCC, "pcc"),
    BRH(Language.BRH, "brh"),
    BUG(Language.BUG, "bug"),
    WES(Language.WES, "wes"),
    YUE(Language.YUE, "yue"),
    TZM(Language.TZM, "tzm"),
    SHU(Language.SHU, "shu"),
    CE(Language.CE, "ce"),
    HNE(Language.HNE, "hne"),
    CTG(Language.CTG, "ctg"),
    CV(Language.CV, "cv"),
    DGA(Language.DGA, "dga"),
    DAG(Language.DAG, "dag"),
    PRS(Language.PRS, "prs"),
    DHD(Language.DHD, "dhd"),
    DIN(Language.DIN, "din"),
    DYU(Language.DYU, "dyu"),
    RMT(Language.RMT, "rmt"),
    CDO(Language.CDO, "cdo"),
    TAJ(Language.TAJ, "taj"),
    BIN(Language.BIN, "bin"),
    EFI(Language.EFI, "efi"),
    ARZ(Language.ARZ, "arz"),
    EGL(Language.EGL, "egl"),
    FON(Language.FON, "fon"),
    FF(Language.FF, "ff"),
    GAN(Language.GAN, "gan"),
    GBM(Language.GBM, "gbm"),
    GRT(Language.GRT, "grt"),
    GPE(Language.GPE, "gpe"),
    GLK(Language.GLK, "glk"),
    GON(Language.GON, "gon"),
    GOR(Language.GOR, "gor"),
    GUW(Language.GUW, "guw"),
    AYH(Language.AYH, "ayh"),
    HAK(Language.HAK, "hak"),
    BGC(Language.BGC, "bgc"),
    MEY(Language.MEY, "mey"),
    HAZ(Language.HAZ, "haz"),
    ACW(Language.ACW, "acw"),
    HIL(Language.HIL, "hil"),
    HOC(Language.HOC, "hoc"),
    CZH(Language.CZH, "czh"),
    IBA(Language.IBA, "iba"),
    IGL(Language.IGL, "igl"),
    ACM(Language.ACM, "acm"),
    TTS(Language.TTS, "tts"),
    JAM(Language.JAM, "jam"),
    CJY(Language.CJY, "cjy"),
    QUC(Language.QUC, "quc"),
    KBD(Language.KBD, "kbd"),
    KBP(Language.KBP, "kbp"),
    KAB(Language.KAB, "kab"),
    KBR(Language.KBR, "kbr"),
    KMC(Language.KMC, "kmc"),
    KAM(Language.KAM, "kam"),
    KR(Language.KR, "kr"),
    PAM(Language.PAM, "pam"),
    KAI(Language.KAI, "kai"),
    KRJ(Language.KRJ, "krj"),
    KS(Language.KS, "ks"),
    KHG(Language.KHG, "khg"),
    KHN(Language.KHN, "khn"),
    CGG(Language.CGG, "cgg"),
    KI(Language.KI, "ki"),
    RN(Language.RN, "rn"),
    KG(Language.KG, "kg"),
    KFY(Language.KFY, "kfy"),
    KRU(Language.KRU, "kru"),
    LKI(Language.LKI, "lki"),
    LMN(Language.LMN, "lmn"),
    LAJ(Language.LAJ, "laj"),
    APC(Language.APC, "apc"),
    AYL(Language.AYL, "ayl"),
    LI(Language.LI, "li"),
    LMO(Language.LMO, "lmo"),
    NDS(Language.NDS, "nds"),
    LUA(Language.LUA, "lua"),
    LUO(Language.LUO, "luo"),
    MAD(Language.MAD, "mad"),
    MAG(Language.MAG, "mag"),
    MDH(Language.MDH, "mdh"),
    MAK(Language.MAK, "mak"),
    VMW(Language.VMW, "vmw"),
    KDE(Language.KDE, "kde"),
    MUP(Language.MUP, "mup"),
    BTM(Language.BTM, "btm"),
    MNK(Language.MNK, "mnk"),
    MWR(Language.MWR, "mwr"),
    MZN(Language.MZN, "mzn"),
    MNI(Language.MNI, "mni"),
    WRY(Language.WRY, "wry"),
    MTR(Language.MTR, "mtr"),
    WTM(Language.WTM, "wtm"),
    MIN(Language.MIN, "min"),
    ARY(Language.ARY, "ary"),
    MOS(Language.MOS, "mos"),
    UNR(Language.UNR, "unr"),
    MTQ(Language.MTQ, "mtq"),
    SCK(Language.SCK, "sck"),
    NAP(Language.NAP, "nap"),
    PCM(Language.PCM, "pcm"),
    NOE(Language.NOE, "noe"),
    KXM(Language.KXM, "kxm"),
    LRC(Language.LRC, "lrc"),
    MNP(Language.MNP, "mnp"),
    ND(Language.ND, "nd"),
    NOD(Language.NOD, "nod"),
    II(Language.II, "ii"),
    NYN(Language.NYN, "nyn"),
    PFL(Language.PFL, "pfl"),
    PAG(Language.PAG, "pag"),
    PMS(Language.PMS, "pms"),
    CPX(Language.CPX, "cpx"),
    RAJ(Language.RAJ, "raj"),
    RHG(Language.RHG, "rhg"),
    RGN(Language.RGN, "rgn"),
    ROM(Language.ROM, "rom"),
    KSW(Language.KSW, "ksw"),
    AEC(Language.AEC, "aec"),
    SPV(Language.SPV, "spv"),
    AYN(Language.AYN, "ayn"),
    SG(Language.SG, "sg"),
    SAT(Language.SAT, "sat"),
    SKR(Language.SKR, "skr"),
    SC(Language.SC, "sc"),
    SAS(Language.SAS, "sas"),
    SCO(Language.SCO, "sco"),
    SGW(Language.SGW, "sgw"),
    SRR(Language.SRR, "srr"),
    SHN(Language.SHN, "shn"),
    SHY(Language.SHY, "shy"),
    SHK(Language.SHK, "shk"),
    SCN(Language.SCN, "scn"),
    SID(Language.SID, "sid"),
    SNK(Language.SNK, "snk"),
    AZB(Language.AZB, "azb"),
    SDH(Language.SDH, "sdh"),
    LUZ(Language.LUZ, "luz"),
    NAN(Language.NAN, "nan"),
    SOU(Language.SOU, "sou"),
    APD(Language.APD, "apd"),
    SUK(Language.SUK, "suk"),
    SUS(Language.SUS, "sus"),
    SS(Language.SS, "ss"),
    GSW(Language.GSW, "gsw"),
    SYL(Language.SYL, "syl"),
    ACQ(Language.ACQ, "acq"),
    RIF(Language.RIF, "rif"),
    SHI(Language.SHI, "shi"),
    TSG(Language.TSG, "tsg"),
    BO(Language.BO, "bo"),
    BBC(Language.BBC, "bbc"),
    TPI(Language.TPI, "tpi"),
    TOI(Language.TOI, "toi"),
    TSC(Language.TSC, "tsc"),
    TN(Language.TN, "tn"),
    TMH(Language.TMH, "tmh"),
    TCY(Language.TCY, "tcy"),
    TUM(Language.TUM, "tum"),
    AEB(Language.AEB, "aeb"),
    TYZ(Language.TYZ, "tyz"),
    UMB(Language.UMB, "umb"),
    SXU(Language.SXU, "sxu"),
    URH(Language.URH, "urh"),
    VE(Language.VE, "ve"),
    VEC(Language.VEC, "vec"),
    WAR(Language.WAR, "war"),
    VLS(Language.VLS, "vls"),
    WAL(Language.WAL, "wal"),
    WO(Language.WO, "wo"),
    WUU(Language.WUU, "wuu"),
    HSN(Language.HSN, "hsn"),
    ZZA(Language.ZZA, "zza"),
    ZA(Language.ZA, "za");

    private final Language language;

    @JsonValue
    private final String tag;

    LanguageVariety(Language language, String tag) {
        this.language = language;
        this.tag = tag;
    }

    /** The selectable varieties of a language in display order, including the default for a language with no choice. */
    public static List<LanguageVariety> forLanguage(Language language) {
        return Arrays.stream(values())
                .filter(variety -> variety.language == language)
                .toList();
    }

    /** What a learner holds until they say otherwise: the first row for every supported language. */
    public static Optional<LanguageVariety> defaultFor(Language language) {
        return forLanguage(language).stream().findFirst();
    }

    public boolean isDefault() {
        return defaultFor(language).filter(this::equals).isPresent();
    }

    @JsonCreator
    public static LanguageVariety fromTag(String tag) {
        return Arrays.stream(values())
                .filter(variety -> variety.tag.equalsIgnoreCase(tag))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("Unknown language variety: " + tag));
    }
}
