name: Build Only

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to build the latest commit from.'
        required: true
        default: 'develop'

permissions:
  contents: read
  packages: write # Needs write permission

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the specified branch to get its SHA
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Call Reusable Build Workflow
        uses: ./.github/workflows/reusable-build.yaml
        with:
          image_tag: ${{ github.sha }}
