name: Build Only

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to build the latest commit from.'
        required: true
        default: 'develop'

permissions:
  contents: read
  packages: write

jobs:
  get-sha:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.sha_step.outputs.sha }}
    steps:
      - name: Checkout the specified branch to get its SHA
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Get the commit SHA
        id: sha_step
        run: echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT

  build:
    needs: get-sha
    uses: ./.github/workflows/reusable-build.yaml
    with:
      image_tag: ${{ needs.get-sha.outputs.commit_sha }}
