name: Deploy BE to Production

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Specify image tag (git SHA) to deploy. Leave blank to build from the latest `main` branch commit.'
        required: false
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build_or_resolve:
    uses: ./.github/workflows/reusable-build-pipeline.yaml
    with:
      image_tag: ${{ inputs.image_tag }}
      source_branch: main
    secrets: inherit

  deploy:
    needs: build_or_resolve
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      environment_name: prod
      ansible_target_group: prod_servers
      image_tag: ${{ needs.build_or_resolve.outputs.image_tag_to_deploy }}
    secrets: inherit
