name: Deploy BE to Staging

on:
  push:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Specify the image tag (git SHA) to deploy. Leave blank to build from the latest `develop` branch commit.'
        required: false
        type: string

jobs:
  run-staging-pipeline:
    uses: ./.github/workflows/reusable-orchestrator.yaml
    with:
      environment_name: staging
      source_branch: develop
      ansible_target_group: staging_servers
      image_tag: ${{ inputs.image_tag }}
    secrets: inherit
