name: Build & Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'maven'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (Multi-Platform)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/almonium-platform/almonium-be:${{ github.sha }}
            ghcr.io/almonium-platform/almonium-be:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          builder: ${{ steps.buildx.outputs.name }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.CLOUD_HOST }}
          username: almonium
          key: ${{ secrets.CLOUD_KEY }}
          envs: |
            # Deployment specific 
            DEPLOY_IMAGE_TAG="${{ github.sha }}"
            DEPLOY_GH_ACTOR="${{ github.actor }}"
            DEPLOY_GH_TOKEN="${{ secrets.GITHUB_TOKEN }}" 

            # Server Configuration (using vars and secrets)
            CONF_LOCAL_PORT=${{ vars.LOCAL_PORT }}
            CONF_DEBUG_PORT=${{ vars.DEBUG_PORT }}
            CONF_SPRING_PROFILE=${{ vars.SPRING_PROFILE }}

            # JWT Configuration
            CONF_JWT_SECRET=${{ secrets.JWT_SECRET }}

            # Database Configuration
            CONF_DB_NAME=${{ vars.DB_NAME }}
            CONF_DB_HOST=${{ vars.DB_HOST }}
            CONF_DB_PORT=${{ vars.DB_PORT }}
            CONF_DB_USERNAME=${{ secrets.DB_USERNAME }}
            CONF_DB_PASSWORD=${{ secrets.DB_PASSWORD }}

            # API Keys
            CONF_RAPID_API_KEY=${{ secrets.RAPID_API_KEY }}
            CONF_WORDNIK_KEY=${{ secrets.WORDNIK_KEY }}
            CONF_YANDEX_KEY=${{ secrets.YANDEX_KEY }}
            CONF_OPENAI_KEY=${{ secrets.OPENAI_KEY }}

            # Stripe Configuration
            CONF_STRIPE_KEY=${{ secrets.STRIPE_KEY }}
            CONF_STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}

            # Stream Configuration
            CONF_STREAM_KEY=${{ secrets.STREAM_KEY }}
            CONF_STREAM_SECRET=${{ secrets.STREAM_SECRET }}

            # Google Cloud Configuration
            CONF_GOOGLE_PROJECT_ID=${{ vars.GOOGLE_PROJECT_ID }}
            CONF_GOOGLE_SERVICE_ACCOUNT_KEY_BASE64=${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY_BASE64 }}

            # Firebase Configuration
            CONF_FIREBASE_STORAGE_BUCKET=${{ vars.FIREBASE_STORAGE_BUCKET }}

            # OAuth2 Configuration
            CONF_GOOGLE_ID=${{ vars.GOOGLE_ID }}
            CONF_GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }}
            CONF_FACEBOOK_ID=${{ vars.FACEBOOK_ID }}
            CONF_FACEBOOK_SECRET=${{ secrets.FACEBOOK_SECRET }}
            CONF_APPLE_ID=${{ vars.APPLE_ID }}
            CONF_APPLE_SECRET=${{ secrets.APPLE_SECRET }}

            # Mail Configuration
            CONF_MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
            CONF_MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          script: |
            echo "--- STARTING DEBUG IN SCRIPT BLOCK ---"
            echo "1. Value of github.sha directly from context: '${{ github.sha }}'"
            echo "2. Value of DEPLOY_IMAGE_TAG env var: '$DEPLOY_IMAGE_TAG'" # THIS IS THE CRITICAL ONE
            echo "3. Value of DEPLOY_GH_ACTOR env var: '$DEPLOY_GH_ACTOR'"
            echo "4. Value of DEPLOY_GH_TOKEN env var (first 5 chars for check): '${DEPLOY_GH_TOKEN:0:5}'"

            if [ -z "$DEPLOY_IMAGE_TAG" ]; then # Check if it's empty *before* calling deploy.sh
              echo "ERROR_DEBUG: DEPLOY_IMAGE_TAG is indeed empty or not set within the script block when trying to pass it to deploy.sh!"
              exit 1 # Fail fast if it's empty here, proves the issue is before deploy.sh
            else
              echo "INFO_DEBUG: DEPLOY_IMAGE_TAG is set to '$DEPLOY_IMAGE_TAG'. Attempting to call deploy.sh."
            fi

            echo "Attempting docker login..." # This might also fail if DEPLOY_GH_ACTOR or _TOKEN are empty
            echo "$DEPLOY_GH_TOKEN" | docker login ghcr.io -u "$DEPLOY_GH_ACTOR" --password-stdin
            echo "Docker login command executed."

            echo "Attempting to call deploy.sh with argument: '$DEPLOY_IMAGE_TAG'"
            /home/almonium/infra/deploy.sh "$DEPLOY_IMAGE_TAG"
            echo "--- FINISHED DEBUG IN SCRIPT BLOCK ---"
