name: Deploy BE to Production

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Specify image tag (git SHA) to deploy. Leave blank to build from the latest `main` branch commit.'
        required: false
        type: string

jobs:
  run-prod-pipeline:
    uses: ./.github/workflows/reusable-orchestrator.yaml
    with:
      environment_name: prod
      source_branch: main
      ansible_target_group: prod_servers
      image_tag: ${{ inputs.image_tag }}
    secrets: inherit
