name: Build & Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'maven'

      - name: Build and Test with Maven
        run: mvn -B verify -DskipITs
        # Assuming mocks are handled via @Import in tests now
        # env:
        #   GOOGLE_SERVICE_ACCOUNT_KEY_BASE64: ${{ secrets.GOOGLE_SA_KEY_BASE64 }}

      # <<< --- ADD THIS STEP --- >>>
      - name: Check for JAR file existence
        run: |
          echo "Listing contents of workspace root:"
          ls -la
          echo "Checking target directory:"
          if [ -d "target" ]; then
            echo "target/ directory exists."
            echo "Listing contents of target/:"
            ls -l target/
            echo "Checking for target/*.jar:"
            if ls target/*.jar 1> /dev/null 2>&1; then
              echo "JAR file found in target/."
            else
              echo "ERROR: JAR file NOT found in target/."
              exit 1 # Fail the workflow if JAR is missing
            fi
          else
            echo "ERROR: target/ directory does NOT exist."
            exit 1 # Fail the workflow if target dir is missing
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/okuzan/almonium-backend:${{ github.sha }}
            ghcr.io/okuzan/almonium-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HTZ_HOST }}
          username: almonium
          key: ${{ secrets.HTZ_KEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            sudo /usr/local/bin/deploy.sh ${{ github.sha }}
