name: Deploy BE to Staging

on:
  push:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Specify the image tag (git SHA) to deploy. Leave blank to build from the latest `develop` branch commit.'
        required: false
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build_or_resolve:
    uses: ./.github/workflows/reusable-build-pipeline.yaml
    with:
      image_tag: ${{ inputs.image_tag }}
      source_branch: develop
    secrets: inherit

  deploy:
    needs: build_or_resolve
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      environment_name: staging
      ansible_target_group: staging_servers
      image_tag: ${{ needs.build_or_resolve.outputs.image_tag_to_deploy }}
    secrets: inherit
