name: Deploy Only

on:
  workflow_dispatch:
    inputs:
      image_digest:
        description: 'The immutable image digest (sha256:...).'
        required: true
      environment:
        description: 'The environment to deploy to.'
        required: true
        type: choice
        options:
          - staging
          - prod

permissions:
  contents: read
  packages: read # Only needs read permission

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      environment_name: ${{ inputs.environment }}
      image_digest: ${{ inputs.image_digest }}
    secrets: inherit
