name: Build & Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'maven'

      - name: Set up Google Cloud Credentials
        run: |
          echo "Creating Google credentials file..."
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > ${{ github.workspace }}/google-credentials.json
          echo "Setting GOOGLE_APPLICATION_CREDENTIALS environment variable..."
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/google-credentials.json" >> $GITHUB_ENV
          echo "Credentials file created and environment variable set."

      - name: Build and Test with Maven
        run: mvn -B verify

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/okuzan/almonium-backend:${{ github.sha }}
            ghcr.io/okuzan/almonium-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HTZ_HOST }}
          username: almonium
          key: ${{ secrets.HTZ_KEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            sudo /usr/local/bin/deploy.sh ${{ github.sha }}
