name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'OPTIONAL: Specify an existing image tag to re-deploy.'
        required: false

permissions:
  contents: read
  packages: write

jobs:
  run-pipeline:
    uses: ./.github/workflows/reusable-build-and-deploy.yaml
    with:
      environment_name: prod
      source_branch: main
      ansible_target_group: prod_servers
      image_tag: ${{ inputs.image_tag }}
    secrets: inherit
