name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      image_digest:
        description: 'OPTIONAL: Promote or re-deploy an existing immutable image digest.'
        required: false

permissions:
  contents: read
  packages: write

jobs:
  run-pipeline:
    uses: ./.github/workflows/reusable-build-and-deploy.yaml
    with:
      environment_name: prod
      source_branch: main
      image_digest: ${{ inputs.image_digest }}
    secrets: inherit
