# This is a reusable workflow that orchestrates the build and deploy steps.
# It takes the environment-specific parameters as direct inputs.

name: Reusable Orchestrator

on:
  workflow_call:
    inputs:
      # --- Parameters that differ between environments ---
      environment_name:
        description: 'The target environment name (e.g., "staging", "prod"). Used for GitHub Environments.'
        required: true
        type: string
      source_branch:
        description: 'The branch to build from if no image_tag is provided (e.g., "develop", "main").'
        required: true
        type: string
      ansible_target_group:
        description: 'The Ansible inventory group to target (e.g., "staging_servers", "prod_servers").'
        required: true
        type: string
      # --- Common parameters ---
      image_tag:
        description: 'Optional specific image tag to deploy. If blank, a new one is built.'
        required: false
        type: string
    secrets: inherit

jobs:
  # STEP 1: Decide on a tag and build it if needed.
  build_or_resolve:
    uses: ./.github/workflows/reusable-build-pipeline.yaml
    with:
      image_tag: ${{ inputs.image_tag }}
      source_branch: ${{ inputs.source_branch }}
    secrets: inherit

  # STEP 2: Deploy the resulting image.
  deploy:
    needs: build_or_resolve
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      environment_name: ${{ inputs.environment_name }}
      ansible_target_group: ${{ inputs.ansible_target_group }}
      # This output comes from the `build_or_resolve` job defined *within this file*.
      image_tag: ${{ needs.build_or_resolve.outputs.image_tag_to_deploy }}
    secrets: inherit
