name: Reusable Build Pipeline

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'Optional image tag to redeploy. If blank, a new one is built.'
        required: false
        type: string
      source_branch:
        description: 'The branch to build from if image_tag is not provided (e.g., main, develop).'
        required: true
        type: string
    outputs:
      image_tag_to_deploy:
        description: "The final image tag that should be deployed."
        value: ${{ jobs.resolve-image.outputs.tag }}
    secrets: inherit

jobs:
  resolve-image:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
      build_needed: ${{ steps.get_tag.outputs.build_needed }}
    steps:
      - name: Checkout source branch for SHA
        uses: actions/checkout@v4
        if: inputs.image_tag == ''
        with:
          ref: ${{ inputs.source_branch }}
      - id: get_tag
        run: |
          if [[ -n "${{ inputs.image_tag }}" ]]; then
            echo "Re-deploying specified tag: ${{ inputs.image_tag }}"
            echo "tag=${{ inputs.image_tag }}" >> $GITHUB_OUTPUT
            echo "build_needed=false" >> $GITHUB_OUTPUT
          else
            echo "Building latest commit from '${{ inputs.source_branch }}' branch."
            echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
            echo "build_needed=true" >> $GITHUB_OUTPUT
          fi

  build:
    needs: resolve-image
    if: needs.resolve-image.outputs.build_needed == 'true'
    uses: ./.github/workflows/build.yaml
    with:
      image_tag: ${{ needs.resolve-image.outputs.tag }}
    secrets: inherit
