name: Reusable Deploy BE

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
      ansible_target_group:
        required: true
        type: string
      image_tag:
        required: true
        type: string
    secrets:
      INFRA_REPO_CHECKOUT_KEY:
        required: true
      CLOUD_KEY:
        required: true
      ANSIBLE_VAULT_PASSWORD:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    permissions:
      packages: read # This job only needs to read from GHCR
    steps:
      - name: Checkout almonium-infra repository
        uses: actions/checkout@v4
        with:
          repository: almonium-platform/almonium-infra
          path: almonium-infra
          ssh-key: ${{ secrets.INFRA_REPO_CHECKOUT_KEY }}
      - name: Set up SSH Agent for Ansible to connect to VM
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.CLOUD_KEY }}
      - name: Install Ansible and Docker collection
        run: |
          python -m venv ansible_venv
          source ansible_venv/bin/activate
          pip install ansible
          ansible-galaxy collection install community.docker
      - name: Set Environment-Specific Vault Password
        id: set_vault_password
        run: |
         if [ "${{ inputs.environment_name }}" == "prod" ]; then
           echo "ANSIBLE_VAULT_PASSWORD_ENV=${{ secrets.ANSIBLE_VAULT_PASSWORD_PROD }}" >> $GITHUB_ENV
         else
           echo "ANSIBLE_VAULT_PASSWORD_ENV=${{ secrets.ANSIBLE_VAULT_PASSWORD_STAGING }}" >> $GITHUB_ENV
         fi

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_VAULT_PASSWORD_ALL: ${{ secrets.ANSIBLE_VAULT_PASSWORD_ALL }}
          ANSIBLE_VAULT_PASSWORD_ENV: ${{ env.ANSIBLE_VAULT_PASSWORD_ENV }}
        run: |
          source ansible_venv/bin/activate
          cd almonium-infra/ansible
          ansible-playbook playbook-deploy-almonium-be.yaml \
           -i "inventory/${{ inputs.environment_name }}.ini" \
           --limit "${{ inputs.ansible_target_group }}" \
           --vault-id "all@env:ANSIBLE_VAULT_PASSWORD_ALL" \
           --vault-id "${{ inputs.environment_name }}@env:ANSIBLE_VAULT_PASSWORD_ENV" \
           --extra-vars "deploy_environment=${{ inputs.environment_name }}" \
           --extra-vars "deploy_image_tag=${{ inputs.image_tag }}" \
           --extra-vars "deploy_gh_actor=${{ github.actor }}" \
           --extra-vars "deploy_gh_token=${{ secrets.GITHUB_TOKEN }}"
