name: Reusable Build BE

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'The tag for the Docker image (e.g., the git SHA)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # This job needs `write` permission to GHCR
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21 and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build JAR with Maven
        run: mvn -B package -Dmaven.test.skip=true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ghcr.io/almonium-platform/almonium-be:${{ inputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
