name: Reusable Orchestrator

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
      source_branch:
        required: true
        type: string
      ansible_target_group:
        required: true
        type: string
      image_tag:
        required: false
        type: string

    secrets:
      INFRA_REPO_CHECKOUT_KEY:
        required: true
      CLOUD_KEY:
        required: true
      ANSIBLE_VAULT_PASSWORD:
        required: true

jobs:
  build_or_resolve:
    uses: ./.github/workflows/reusable-build-pipeline.yaml
    with:
      image_tag: ${{ inputs.image_tag }}
      source_branch: ${{ inputs.source_branch }}

  # This job correctly passes the secrets it received on to the deploy workflow.
  deploy:
    needs: build_or_resolve
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      environment_name: ${{ inputs.environment_name }}
      ansible_target_group: ${{ inputs.ansible_target_group }}
      image_tag: ${{ needs.build_or_resolve.outputs.image_tag_to_deploy }}
    secrets:
      INFRA_REPO_CHECKOUT_KEY: ${{ secrets.INFRA_REPO_CHECKOUT_KEY }}
      CLOUD_KEY: ${{ secrets.CLOUD_KEY }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
