name: Deploy to Staging

on:
  push:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'OPTIONAL: Specify an existing image tag to re-deploy.'
        required: false
        type: string

permissions:
  contents: read
  packages: write

jobs:
  run-pipeline:
    uses: ./.github/workflows/reusable-build-and-deploy.yaml
    with:
      environment_name: staging
      source_branch: develop
      ansible_target_group: staging_servers
      image_tag: ${{ inputs.image_tag }}
    secrets: inherit
